### ISSUE TITLE
2D grid verification visualization

### ISSUE THREAD

**Issue by jrdelph** [cascadiaquakes/CRESCENT-CVM#9]
I tested the cvm_writer for creating 2D surfaces but noticed that there is no way to visualize the data to ensure that it was properly uploaded (through cvm_slicer.py). It seems like it would be good if we could find a way to plot the surfaces prior to them being submitted to the CVM repository.

Perhaps we can add an input into cvm_slicer to have the user tell us that it is a "surface" or "volume" that we are trying to plot. If it is a surface, we could have it just plot all the data as is (or keep the subset, etc), but we probably only need a mapview.

Also, there is also a small typo in the Step 7 of both the 3D and 2D cvm_writer instructions:
"python ../../src/netCDF_summary_info.py" should be "python ../../src/netcdf_summary_info.py"

**Comment by manoch-iris** [comment]
2D support is added to the cvm_slicer tool and the typo is corrected (thank you!)
